### ISSUE TITLE
0 Length jvm.cfg file.

### ISSUE THREAD

**Issue by magno32** [woglinde/meta-java#46]
When building the java-test-image, or adding IMAGE_INSTALL_append += " openjdk-7-vm-jamvm" to my local recipe, the jre/lib/arm/jvm.cfg file becomes empty.  The alternate VM's do work, however, if they are manually added to the empty file, i.e. "-jamvm KNOWN"

**Comment by woglinde** [comment]
meta-java has moved you can find it now under

git://git.yoctoproject.org/meta-java
