### ISSUE TITLE
Jamvm-native libFFI patch issue

### ISSUE THREAD

**Issue by ZARk-be** [woglinde/meta-java#63]
Hello

Trying to build jamvm-native using bitbake, and getting errors with the configure script
basically the LIBFFI patch patches configure.ac but somehow some macros are left over, therefore configure fails to run
manually running "autoreconf" fixes it, but bitbake will re-run all scripts in there and block things.
I'm trying to figure out how this all works to fix it, but ain't easy

Oh, i'm trying to build on newest Angstrom 2014.6.
Host system is Gentoo x86

**Comment by woglinde** [comment]
meta-java has moved you can find it now under

git://git.yoctoproject.org/meta-java
