### ISSUE TITLE
Are there any example recipes for libraries that use JNI?

### ISSUE THREAD

**Issue by johntconklin** [woglinde/meta-java#72]
I'm working on a recipe for jzmq, and I'm stumbling over how to determine the paths to the jni.h and jni_md.h headers.  Are there any existing recipes for libraries that use JNI that I can use as a reference?

For the time being, I'm hard-coding paths to tmp/sysroots/genericx86-64/usr/lib/jvm/java-7-openjdk/include, etc.  But that's not going to work for other targets.

**Comment by woglinde** [comment]
meta-java has moved you can find it now under

git://git.yoctoproject.org/meta-java
