### ISSUE TITLE
Daisy and Dora

### ISSUE THREAD

**Issue by mindrunner** [woglinde/meta-java#73]
Hi guys, just about to re-enable my buildbot.

So we have a dora branch here for Yocto 1.5.x and a master branch for yocto-development? 
Is there anything for Yocto 1.6.x (Daisy)? Has anyone tested master or dora branch of meta-java with Yocto 1.6?

Cheers,
Lukas

**Comment by woglinde** [comment]
meta-java has moved you can find it now under

git://git.yoctoproject.org/meta-java
