### ISSUE TITLE
icedtea6-native_1.8.11 build error

### ISSUE THREAD

**Issue by mindrunner** [woglinde/meta-java#74]
Hi, 
I am trying to build yocto/oe daisy branch using meta-java master branch. Getting the following error:

http://pastebin.com/L3pDvq62
 
Any ideas?

**Comment by mirzak** [comment]
Did you resolve this? 

I am getting the same error on meta-java dora branch now. It worked fine on Ubuntu 14.04 LTS but upgraded to Ubuntu 14.10 and got this error.

**Comment by mindrunner** [comment]
I resolved it, but I cant remember how. I also switched to daisy, so havent tried any Dora build for a couple of weeks.

**Comment by woglinde** [comment]
meta-java has moved you can now find it under

git://git.yoctoproject.org/meta-java
