### ISSUE TITLE
openjdk-7 recipy do_install ERROR: cp: cannot stat /.../j2sdk-image

### ISSUE THREAD

**Issue by pompomJuice** [woglinde/meta-java#82]
I  have no idea why this has not been picked up before, but at least on my environment there seems to be a very small error inside the openjdk-7 recipe's do_install. I found that a ${WORKDIR} should be a ${S}.

I am at revision d2b75b615e4612f9fa05950c1d76d4a719e573d4

The following patch sorts it out for me:

    diff --git a/recipes-core/openjdk/openjdk-7-common.inc b/recipes-core/openjdk/openjdk-7-common.inc
    index 32fab16..4a08fe8 100644
    --- a/recipes-core/openjdk/openjdk-7-common.inc
    +++ b/recipes-core/openjdk/openjdk-7-common.inc
    @@ -172,7 +172,7 @@ do_compile() {
 
     do_install() {
            install -d ${D}${libdir_jvm}
    -       cp -R ${WORKDIR}/build/${BUILD_DIR}/j2sdk-image ${D}${JDK_HOME}
    +       cp -R ${S}/build/${BUILD_DIR}/j2sdk-image ${D}${JDK_HOME}
 
            chmod u+rw -R ${D}${JDK_HOME}

**Comment by woglinde** [comment]
Thanks for the patch, but we got it serval times and it is nor your fault that I not yet updated my README to point to the new location of the meta-java layer at git://git.yoctoproject.org/meta-java
